# Site settings
title: Casey Lawrence
description: Casey Lawrence's personal page

# User settings
username: Casey Lawrence
user_description:
user_title: Software Developer
email: casey.j.lawrence@gmail.com
twitter_username: casey_lawr
github_username:  cjlaw
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
