# Site settings
title: Casey Lawrence
description: Casey Lawrence, Software Developer
website: https://caseylawrence.dev/

# User settings
username: Casey Lawrence
user_description:
user_title: Software Developer
email: casey.j.lawrence@gmail.com
github_username: cjlaw
linkedin_username: casey-lawrence-b03b3b86

# Google-analytics
google-analytics:
  id:

exclude: ['package.json', 'src' , 'node_modules']
