title: Casey Lawrence
description: Casey Lawrence
website: https://caseylawrence.dev/

username: Casey Lawrence
user_title: Tech Lead & Full-Stack Developer
email: casey.j.lawrence@gmail.com
github_username: cjlaw
linkedin_username: casey-lawrence-b03b3b86

